#!/usr/bin/env python3
"""Regenerate requirements.yml, the README collection table and the ansible-core pin from an Ansible community release.

The collection set is the one shipped in the `ansible` community package (curated
and maintained upstream), plus the extras in extra-collections.txt (pinned to their
latest Galaxy release). Collections in excluded-collections.txt are dropped.

Usage: scripts/update-requirements.py [ANSIBLE_VERSION]   (default: latest on PyPI)
"""
import json
import pathlib
import re
import ssl
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUILD_DATA = "https://raw.githubusercontent.com/ansible-community/ansible-build-data/main/{major}/ansible-{version}.deps"
GALAXY = "https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/index/{ns}/{name}/"


def ssl_context():
    try:
        import certifi
        return ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        return ssl.create_default_context()


CTX = ssl_context()


def fetch(url):
    with urllib.request.urlopen(url, timeout=60, context=CTX) as r:
        return r.read().decode()


def read_list(name):
    path = ROOT / name
    if not path.exists():
        return []
    return [l.split("#")[0].strip() for l in path.read_text().splitlines() if l.split("#")[0].strip()]


def main():
    version = sys.argv[1] if len(sys.argv) > 1 else json.loads(fetch("https://pypi.org/pypi/ansible/json"))["info"]["version"]
    deps = {}
    for line in fetch(BUILD_DATA.format(major=version.split(".")[0], version=version)).splitlines():
        key, _, value = line.partition(":")
        deps[key.strip()] = value.strip()
    core = deps.pop("_ansible_core_version")
    collections = {k: v for k, v in deps.items() if not k.startswith("_")}

    for name in read_list("excluded-collections.txt"):
        collections.pop(name, None)
    extras = {}
    for name in read_list("extra-collections.txt"):
        ns, coll = name.split(".")
        extras[name] = json.loads(fetch(GALAXY.format(ns=ns, name=coll)))["highest_version"]["version"]

    out = [
        "---",
        f"# Generated by scripts/update-requirements.py from ansible {version} (ansible-core {core}).",
        "# Edit extra-collections.txt / excluded-collections.txt and re-run instead of editing by hand.",
        "collections:",
        f"  # Collections shipped in the ansible {version} community package",
    ]
    out += [f"  - {{name: {n}, version: {v}}}" for n, v in sorted(collections.items())]
    if extras:
        out.append("  # Extras from extra-collections.txt (latest Galaxy release)")
        out += [f"  - {{name: {n}, version: {v}}}" for n, v in sorted(extras.items())]
    (ROOT / "requirements.yml").write_text("\n".join(out) + "\n")

    rows = [f"| `{n}` | {v} | bundled |" for n, v in sorted(collections.items())]
    rows += [f"| `{n}` | {v} | extra |" for n, v in sorted(extras.items())]
    table = "\n".join([
        f"**ansible {version}** · **ansible-core {core}** · {len(collections) + len(extras)} collections",
        "",
        "<details>",
        "<summary>Show all collections</summary>",
        "",
        "| Collection | Version | Source |",
        "|---|---|---|",
        *rows,
        "",
        "</details>",
    ])
    readme = ROOT / "README.md"
    readme.write_text(re.sub(
        r"(<!-- BEGIN collections -->\n).*?(<!-- END collections -->)",
        lambda m: f"{m.group(1)}{table}\n{m.group(2)}",
        readme.read_text(),
        flags=re.S,
    ))

    ee = ROOT / "execution-environment.yml"
    text = re.sub(r"ansible-core==[\w.]+", f"ansible-core=={core}", ee.read_text())
    text = re.sub(r"(org\.ansible\.version=)[\w.]+", rf"\g<1>{version}", text)
    text = re.sub(r"(org\.ansible\.core-version=)[\w.]+", rf"\g<1>{core}", text)
    ee.write_text(text)
    print(f"ansible {version} / ansible-core {core}: {len(collections)} bundled + {len(extras)} extra collections")


if __name__ == "__main__":
    main()
